### PR TITLE
fix(locale): align language handling with IDE settings (fixes #308)

### LINKED ISSUE #308: Improved locale handling for non-English IDE configurations
When using the plugin with:
English IDE + non-English OS locale, or
Non-English IDE + different OS locale

The locale display and LLM instructions could show unexpected language names due that plugin takes locales from OS locale and not IDE locale. This also probably causes confusion for some LLMs when generating commit messages.

In my case of Czech OS Windows, and Jetbrains IDE in English it listed languages names in Czech. It looked out of place in English ide. Also some smaller LLMs had a trouble use correct language for git commits. 

Prompt is:
`"Use {locale} language to answer." `

So in my case it was: 
`"Use {angličtina (note: angličtina is Czech name fro English language)} language to answer."` And this gave me mostly commit messages in English (correct), but sometimes it gave me commit messages in Czech (not correct). This happened to me with Llama 3.3 70b (and conventional commits). Bigger models like Sonnet were fine.

Also sorting in non English locales dont work properly with some unique symbols. For example Č for Čeština should be between C and D. Currently shows at the end. Example of sorting of unique characters at the end after z symbol:

Image

Proposed Solution:
1. Use IDE's UI locale instead of system locale for language displays
2. Standardize locale formatting in prompt to English Name (ISO 639) – Native Name; example "French (fr) – français"
3. Implement proper collation for locale list sorting

### PR DESCRIPTION
**Pull request by Canario5**
Fixes #308 - Improved locale handling for non-English IDE configurations

### Changes:
- Use IDE locale instead of OS system for language displays in settings
- Implement Collator-based sorting for locale list
- Standardize prompt locale to 'English name (code) – Native name'; example "French (fr) – français"

### CODE REVIEW

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt [hunk 1]
```diff
@@ -39,7 +41,8 @@ object AICommitsUtils {
     fun constructPrompt(promptContent: String, diff: String, branch: String, hint: String?, project: Project): String {
         var content = promptContent
         val locale = project.service<ProjectSettings>().locale
-        content = content.replace("{locale}", locale.displayLanguage)
+        // lang format: "Language name in English + (ISO 639 lang code) + – + native language name in IDE's locale"; example "French (fr) – français"
```
Comment (Blarc) [inline src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt:44]: I feel like this is a bit much and could be changed to just `locale.getDisplayLanguage(Local.ENGLISH)`. If someone wants to be this specific, they could just make a customized prompt with hardcoded language.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt [hunk 2]
```diff
@@ -173,4 +176,8 @@ object AICommitsUtils {
             false
         )
     }
+
+    fun getIDELocale(): Locale {
+        return DynamicBundle.getLocale() ?: Locale.getDefault()
```
Comment (Blarc) [inline src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt:181]: Elvis operator (?:) always returns the left operand of non-nullable type Locale. Elvis operator can be removed.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt [hunk 3]
```diff
@@ -18,7 +19,9 @@ class AICommitsListCellRenderer : DefaultListCellRenderer() {
         val component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus)
         when (value) {
             is Locale -> {
-                text = value.displayLanguage
+                val ideLocale = AICommitsUtils.getIDELocale()
+                // lang format: "Language name in IDE's locale + (ISO 639 lang code)"; example for Spanish in IDE "francés (fr)", for IDE in German "Französisch (fr)"
+                text = "${Locale(value.language).getDisplayName(ideLocale)} (${value.language})"
```
Comment (Blarc) [inline src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt:24]: `Local(value.language)` is deprecated, please replace with something appropriate.
I also think, it would make more sense to use the same language format that is used when creating the prompt, so `getDisplayName(ENGLISH)`, to not confuse the user what goes into the prompt.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AppSettingsConfigurable.kt [hunk 4]
```diff
@@ -78,11 +80,23 @@ class AppSettingsConfigurable(val project: Project, cs: CoroutineScope) : BoundC
 
         row {
             label(message("settings.locale")).widthGroup("labelPrompt")
-            comboBox(Locale.getAvailableLocales()
```
Comment (Blarc) [inline src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AppSettingsConfigurable.kt:81]: Please add a comment about what this collator does and why was it added.

**Review by Blarc — CHANGES_REQUESTED** [review]
Hey @Canario5,

thanks a lot for opening a PR. The changes you've suggested make a lot of sense. There are just a few nitpicks I'd like to go over with you, before I merge this :pray:.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt (hunk 3 above)
Comment (Blarc) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt:24]: I am not 100% though, what is the best way to display the language here... Your way makes a lot of sense as well... I'm open for debate.

Comment (Canario5) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt:24]: Number are in order you created the comments. I will answer in one long comment because i consider these things very connected. I see two ways:

### A) Everything needs to be in English.
That means deleting **2)** because DynamicBundle.getLocale() takes the language from the IDE, which can be something different than English. 

**1 and 3** need to be hardcoded in English as well. 

And **4** needs to be removed because it can sort languages in the current language, which might not be English.

### Solution B) (My implementation)

**2** DynamicBundle.getLocale() takes the language from the IDE, which can be something other than English.

**4** Is sorting languages. If 2) can be non-English, then Collator is needed because it correctly sorts languages in their native languages. Old sorting will fail in many occasions, such as RTL languages (e.g., Arabic) being sorted incorrectly (although i didnt test it personally that my implementation plays well with RTL languages...). Special and unique characters will also be sorted incorrectly. For example, in Czech, the character "č" should be placed between the letters "c" and "d." Old sorting would place "č" at the end of the alphabet due to its Unicode position. There are other occassions which should Collator theoreticaly do better than classic sort.

**3** This is a language listing. This needs to use the same language that is used for sorting. If sorting is done in the local language with Collator (e.g., Czech) and listing is in English, then some languages will appear in improper positions. For example, "Catalan" will be shown in English but is "Katalánština" in Czech. So user would get "Catalan" listed between languages starting with letter "K" in English.

**1** Okay, here it can be hardcoded in English only, and it would work in both cases. I agree that at first (and even second) glance, the code looks rough :) But I think hardcoding English will take away at least one thing for users—the ability to use the {locale} variable in their localized prompts. Maybe the format "French (fr) – français" looks unwieldy, but it seems to me robust enough to work for English and non-English languages. However, I don’t have a problem if this is hardcoded in English (although personally, hardcoding anything feels a little wrong to me, but thats just me). I admit that an English-only solution in this step is much cleaner, and I will make the change if you will wish for it.

> "I am not 100% sure what is the best way to display the language here..."

I personaly think that using same language which user using for IDE is most consistent and is small step forward. I think we could add contextHelp next to the locale select box in settings explaining which locale value will actually be used. For example: "French (fr) – français" or just (French locale content will be English only) or something like that. What do you think?

Of course, I may have missed something etc., I’m open to suggestions and changes. Feel free to write anything.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt (hunk 2 above)
Comment (Canario5) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt:181]: You are completely right. If needed I will make the change according what decide in https://github.com/Blarc/ai-commits-intellij-plugin/pull/309#discussion_r1957418224

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt (hunk 3 above)
Comment (Blarc) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt:24]: I like the suggestion with `contextHelp`. This way we can keep the IDE locale to display the languages, but use the English locale for prompt. By adding additional text to the language (e.g French (fr) – français), we'd change the current prompts that users use:
- more tokens, which means the prompt can be more expensive
- different prompt, which can change the result

So I'd rather see if you could make it so the language in the prompt stays the same as now, while the combo box and sorting can be updated, with the added `contextHelp`.

Thanks so much :pray: .

Comment (Blarc) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/settings/AICommitsListCellRenderer.kt:24]: PS: For 4 https://github.com/Blarc/ai-commits-intellij-plugin/pull/309#discussion_r1957361498 I meant if you can add a short comment in the code, so I don't forget why this was added. Thanks.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt (hunk 2 above)
Comment (Canario5) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt]: I removed Elvis operator (?:) and kept getting language from IDE.

File: src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt (hunk 1 above)
Comment (Canario5) [reply src/main/kotlin/com/github/blarc/ai/commits/intellij/plugin/AICommitsUtils.kt]: Changed to English locale names in prompts.

**Comment by Blarc** [comment]
This looks great @Canario5, thank you so much! :100:
